name: test
#This is a GitHub Actions workflow file for building a Maven Package and a Multi-stage Docker image.
#The workflow is triggered on a push event.
#The 'build' job runs on the latest version of Ubuntu and requires permissions to read repository contents and write packages.
#The job outputs the jar version, which will be used in subsequent steps.

on:
  [push]
env:
  REPO: omeili/java-app
jobs:
  set:
    runs-on: ubuntu-latest

    steps:
#Checks out the repository.
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Docker build
      run: |
        docker build . -t ${{  env.REPO  }}:1.0.0 -f DockerMultiStage
    - name: Docker push
      run: |
        docker push ${{  env.REPO  }}:1.0.0
