name: Maven Package - Multi stage docker

on:
  [push]
  
permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jar_version: ${{ steps.bump.outputs.jar_version }}

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Extract latest tag
      id: extract_tag
      run: |
        # Get the latest tag of an image from Docker Hub
        new_version=$(curl -s "https://registry.hub.docker.com/v2/repositories/omeili/java-app/tags/?page_size=1&order=desc" | jq -r '.results[].name')
        echo "Latest tag: ${new_version}"
        echo "::set-output name=tag::${new_version}"
        
    - name: Bump jar version
      id: bump
      run: |
        POMPATH=myapp
        version=${{ steps.extract_tag.outputs.tag }} 
        major=$(echo $version | cut -d. -f1)
        minor=$(echo $version | cut -d. -f2)
        patch=$(echo $version | cut -d. -f3)
        new_version="$major.$minor.$((patch + 1))"
        mvn -f myapp/pom.xml versions:set -DnewVersion=$new_version
        echo ::set-output name=jar_version::${new_version}
        
    - name: Docker build
      run: |
        docker build . -t omeili/java-app:${{ steps.bump.outputs.jar_version }} -f DockerMultiStage
    - name: Docker push
      run: |
        docker push omeili/java-app:${{ steps.bump.outputs.jar_version }}
  run:
    runs-on: ubuntu-18.04
    needs: [build]

    steps:
    - name: Run container
      run: |
        docker run omeili/java-app:${{needs.build.outputs.jar_version}}
